name: debtAllocatorLendingVaultV3
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.0
  # - name: LlamaPay
  #  github: LlamaPay/llamapay
  #  branch: master

solidity: 
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.8.0"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura
